version: "3"
services:
  python:
    image: python:3.5.4-slim
    container_name: srgan
    command: tail -f /dev/null
    networks:
      - netproxy
      - default
    volumes:
      - ${PWD}:/app
    labels:
      - "traefik.enable=true"

networks:
  netproxy:
    external:
      name: netproxy